{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "027c5e3c",
   "metadata": {},
   "outputs": [],
   "source": [
    "import mysql.connector\n",
    "#connecting to mysql\n",
    "mydb=mysql.connector.connect(host=\"localhost\",user=\"root\",passwd=\"swastikabose\",database=\"todo\");\n",
    "#connecting to cursor\n",
    "mycursor=mydb.cursor()\n",
    "\n",
    "#main menu\n",
    "def menu():\n",
    "                print(\"To-Do list\")\n",
    "                print(\"1. Insert to a to-do list\")\n",
    "                print(\"2. Display a to-do list\")\n",
    "                print(\"3. Update date for an event in to-do list\")\n",
    "                print(\"4. Update venue for an event in to-do list\")\n",
    "                print(\"5. Delete from to-do list\")\n",
    "                print(\"6. Exit\")\n",
    "                ch=int(input(\"Enter Choice\"))\n",
    "                if (ch==1):\n",
    "                    insert()\n",
    "                elif (ch==2):\n",
    "                    display()\n",
    "                elif (ch==3):\n",
    "                    upt_time()\n",
    "                elif (ch==4):\n",
    "                    upt_venue()\n",
    "                elif (ch==5):\n",
    "                    delete()\n",
    "                else:\n",
    "                    print(\"Exit\")\n",
    "\n",
    "                             \n",
    "def insert():\n",
    "                print(\"To-Do list\")\n",
    "                ch='y'\n",
    "                while (ch=='y'):\n",
    "                                l=[]\n",
    "                                time=input(\"enter time:\")\n",
    "                                l.append (time)\n",
    "                                work=input(\"enter work to-do:\")\n",
    "                                l.append (work)\n",
    "                                ven=input(\"enter venue(if there)\")\n",
    "                                l.append (ven)\n",
    "                                todo=(l)\n",
    "                                sql=\"insert into todo1 (time,work,ven)values(%s,%s,%s)\"\n",
    "                                mycursor.execute(sql,todo)\n",
    "                                mydb.commit()\n",
    "                                print(\"insertion completed\")\n",
    "                                print(\"Do you want to insert more work\")\n",
    "                                ch=input(\"enter y/n\")\n",
    "                print('\\n' *10)\n",
    "                print(\"==============================================\")\n",
    "                menu()\n",
    "\n",
    "\n",
    "          \n",
    "def delete():\n",
    "                print(\"Delete from To-Do list\")\n",
    "                wo=input(\"enter work to be searched\")\n",
    "                pn=(wo,) \n",
    "                sql=\"delete from todo1 where work=%s\"\n",
    "                mycursor.execute(sql,pn)\n",
    "                mydb.commit()\n",
    "                print(\"Deletion completed\")\n",
    "                print(\"Go back to menu\")\n",
    "                print('\\n' *10)\n",
    "                print(\"==============================================\")\n",
    "                menu()\n",
    "\n",
    "             \n",
    "                \n",
    "def display():\n",
    "                print(\"To-Do List\")\n",
    "                sql=\"select * from todo1\"\n",
    "                mycursor.execute(sql,)\n",
    "                res=mycursor.fetchall() \n",
    "                mydb.commit()\n",
    "                for x in res:\n",
    "                                print(x)   \n",
    "                print(\"Go back to menu\")\n",
    "                print('\\n')               \n",
    "                print(\"==============================================\")\n",
    "                menu()\n",
    "\n",
    "\n",
    "def upt_venue():\n",
    "    \n",
    "                print(\"Update Venue\")\n",
    "                work=input(\"enter event for which venue to be updated: \")\n",
    "                venue=input(\"enter new venue: \")\n",
    "                sql=\"update todo1 set ven=%s where work=%s\"\n",
    "                val=(work, venue)\n",
    "                mycursor.execute(sql,val)\n",
    "                mydb.commit()\n",
    "                print(\"Event Venue Updated\")\n",
    "                print(\"Go back to menu\")\n",
    "                print('\\n')               \n",
    "                print(\"==============================================\")\n",
    "                menu()\n",
    "                \n",
    "                \n",
    "def upt_time():\n",
    "                print(\"Update Time\")\n",
    "                work=input(\"enter event for which time to be updated: \")\n",
    "                time=input(\"enter new time: \")\n",
    "                sql=\"update todo1 set time=%s where work=%s\"\n",
    "                val=(work, time)\n",
    "                mycursor.execute(sql,val)\n",
    "                mydb.commit()\n",
    "                print(\"Event time Updated\")\n",
    "                print(\"Go back to menu\")\n",
    "                print('\\n')               \n",
    "                print(\"==============================================\")\n",
    "                menu()   \n",
    "\n",
    "#main                \n",
    "menu()\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "284b0606",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "eb27226a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
